### ISSUE TITLE
Proper naming of attribute for not setting aa-val-msg

### ISSUE THREAD

**Issue by domderen** [AngularAgility/AngularAgility#103]
Hi,

I saw this line of code: https://github.com/AngularAgility/AngularAgility/blob/master/src/formExtensions/directives/aaField.js#L49

Where the attribute to not append validation messages is called "aanovalmsg". Shouldn't that be "aaNoValMsg", to keep to the same format as with all the other attributes used on elements, where it would be "aa-no-val-msg"?

**Comment by johnculviner** [comment]
good call didn't notice that on a PR a few months ago. putting 'aanovalmsg' as an attribute seems a little wonky vs aa-no-val-msg. Good eye!
