### ISSUE TITLE
Server validations / ajax?

### ISSUE THREAD

**Issue by npearson72** [AngularAgility/AngularAgility#117]
Hi,

I have an email field that gets validated by the server for uniqueness. How can I get this to work with AngularAgility?

Thanks,
Nathan

**Comment by johnculviner** [comment]
You should be able to use async validators:

ex: http://www.codelord.net/2014/11/02/angularjs-1-dot-3-taste-async-validators/

AA should detect the invalidity of the field/form regaurdless of the source of the error.. Let me know if that doesn't work.

**Comment by johnculviner** [comment]
Let me know either way actually, I haven't used them yet but I used to use something similar before it came out

**Comment by npearson72** [comment]
Thanks @johnculviner 

What I ended up doing is adding this to my form submission error response, and it seemed to do the trick:

`$aaFormExtensions.email.$addError("Email is already taken.")`

**Comment by johnculviner** [comment]
Nice, even easier! Thanks for the pointer!
