### ISSUE TITLE
$aaFormExtensions.$reset()

### ISSUE THREAD

**Issue by samrajs** [AngularAgility/AngularAgility#121]
I used $aaFormExtensions.$reset() to reset the form after submit. It works, but it shows a confirmation message before clearing the form. Is there any way to clear a form without showing confirmation message?

Thank you.

**Comment by johnculviner** [comment]
Hey can you show me what you are trying to do? I updated the docs to make things a little more clear.

**Comment by johnculviner** [comment]
https://github.com/AngularAgility/AngularAgility/blob/master/README.md#reset-initial-form-state

**Comment by samrajs** [comment]
This is my form

    <div class="form-horizontal" align="center" ng-form="passChange">
        <input type="text" aa-label="User ID" class="form-control" aa-field-group="user.userId" ng-model="user.userId" required/>
        <input type="password" class="form-control" aa-label="Old Password" aa-field-group="user.oldPassword" name="user.oldPassword" required/>        
        <input type="password" class="form-control" aa-label="New Password" aa-field-group="user.newPassword" name="user.newPassword" required/>
        <input type="password" class="form-control" aa-label="Confirm Password" aa-field-group="user.confirmPassword" name="user.confirmPassword" required/>    
        <div class="row top-buffer">
            <div class="col-md-12" align="center">
                <button type="button" class="btn" aa-submit-form="changePassword()">Change Password</button>
                <button type="button" class="btn" ng-click="reset()">Reset</button>
            </div>
        </div>        
    </div>          

This my java script
```javascript
        $scope.reset = function() {
            console.log( 'Inside reset' );
            console.log( 'Changed :', $scope.passChange.$aaFormExtensions.$changed);
            $scope.passChange.$aaFormExtensions.$resetChanged();
        }
```

I am calling reset() function to clear the form on the click of 'Reset' button and after successfull submission of the form. When I used $resetChanged(), it is not resetting any entered value, but it shows $changed as true. This is the same behaviour in the demo page as well. 

http://angularagility.herokuapp.com/#/formExtensions/formExtensions/advanced

I tried the address form in your demo.

When I used $reset(), it is clearing the form, but unfortunately browser is showing confirmation, "Are you sure you want to reset unsaved changes?". I want a behaviour that clears the form without showing confirmation message.

I might be misusing $reset or $resetChanged to clear forms. In this case, can you please tell me how to clear an aaForm.

Thank you.

**Comment by samrajs** [comment]
Now I did this way. It is working. Is it a right way to clear an aaForm? Thank you.

´´´javascipt
        var emptyUser = {
            userId: "",
            oldPassword: "",
            newPassword: "",
            confirmPassword: ""
        }

        $scope.reset = function() {
            console.log( 'Inside reset' );
            console.log( 'Changed :', $scope.passChange.$aaFormExtensions.$changed);
            $scope.user = angular.copy(emptyUser);
            $scope.passChange.$aaFormExtensions.$clearErrors();
        }
´´´

**Comment by johnculviner** [comment]
Hey yeah,

reset = sets the form back to its initial state (whatever that was when the screen was arrived at)
resetChanged = the current state of the form is now considered the new, unchanged state.

It looks to me like you just want to clear out your object to nothing (which is not the intent of either of those operations) so you could do what you did above and maybe call $resetChanged to say the 'new' state of the form i now considered unchanged. Make sense?

**Comment by samrajs** [comment]
Yes, Thank you.

I will close this topic.

Thanks again.

Regards
Sam
