### ISSUE TITLE
Dynamic Field creation

### ISSUE THREAD

**Issue by webappworks** [AngularAgility/AngularAgility#123]
Is there a way to compile a dynamically built html template that customizes the aa-field attribute?

We have various JSON data layouts and need display / edit forms.

We're using ui-router.  Thx!

**Comment by johnculviner** [comment]
Hey, you should be able to do this with the $injector that is provided to you as part of the method signature. Example here: https://github.com/AngularAgility/AngularAgility/blob/master/src/formExtensions/provider.js#L32

Let me know if that doesn't work and I can try to add something/ re-open the issue. Thanks!
