### ISSUE TITLE
$aaFormExtensions.$clearErrors() invocation triggers 'Error: [$rootScope:inprog] $digest already in progress'

### ISSUE THREAD

**Issue by magicmanam** [AngularAgility/AngularAgility#124]
I have $scope.$watch's listener which calls the following code:

```javascript
$formCtrl.$aaFormExtensions.$clearErrors();
```

This line triggers [$rootScope:inprog] error. In your code I see the following:
            
```javascript
1: function $clearErrors() {
2:             if(!scope.$$phase){
3:                scope.$apply($clearErrors);
4:                return;
5:              }
6:             ....
```
Here scope.$$phase === null and the 3rd line is invoked, but in angular code:

```javascript
1: function beginPhase(phase) {
2:      if ($rootScope.$$phase) {
3:        throw $rootScopeMinErr('inprog', '{0} already in progress', $rootScope.$$phase);
4:     }
```

Here $rootScope.$$phase === '$digest' and the error is thrown.

Could you please take a look into this issue or give me some advice how can I fix it ?

Thanks in advance!

**Comment by johnculviner** [comment]
Hey if you could give me a plunker of it I'll see if there is something better defensively that can be done to prevent that. Haven't ever tried that in the callback for a watch before, interesting....

**Comment by magicmanam** [comment]
Thank you for the quick reply!

Here a [plunker](http://plnkr.co/edit/6WlucSmebqfkqMPmeoIS?p=preview) with steps to reproduce the issue. FormModel directive from the plunker is used to clear aaFormExtensions errors when model is changed (form.$setPristine() is not enough).

I've investigated that the issue is reproduced in 0.8.26 version (when isolated scope is used).
0.8.23 version has no such issue.
I believe this is related to the following [lines](https://github.com/AngularAgility/AngularAgility/blob/master/src/formExtensions/directives/ngForm.js#L315-L318) in $clearErrors() function.

What do you think?

**Comment by johnculviner** [comment]
apparently scope.$$phase isn't enough anymore you need to check scope.$root.$$phase too to make sure a digest isn't already in progress. The latest version should fix the issue, thanks for putting together the plunker!

**Comment by magicmanam** [comment]
Actually, it is because an isolated scope doesn't inherit $$phase property from $rootScope.
Thanks for great support! The latest version fixes the issue!

**Comment by johnculviner** [comment]
Oh interesting. I wonder if it's just possible to digest 1 isolate scope. Angular should just have a safeApply built in!!
