### ISSUE TITLE
Modal open from form with same aa-field-name

### ISSUE THREAD

**Issue by kinnrot** [AngularAgility/AngularAgility#125]
The problem is in the location of the validation message, angular agility does not know that there is a modal opened, and show the validation message in the form element with the same name instead of showing the validation message in the modal field.

**Comment by johnculviner** [comment]
Hey! Yeah it's getting confused because you have the same field names in the same form multiple times. This should fix it for you (just need to make multiple forms, angular and AA have no problem with multiple nested forms: http://plnkr.co/edit/sdHXdBj5FxNnvysMaMZ1?p=preview

This fix it for you?

**Comment by johnculviner** [comment]
Make sure to have your modal wrapped in a ng-form. Also you cannot duplicate field names without making a new (perhaps nested ng-form) I'm going to need a plunker if you need more help and I can re-open. Thanks!
