### ISSUE TITLE
Validation Breaking With Multiple Items with same aa-form-group name

### ISSUE THREAD

**Issue by erikruggles** [AngularAgility/AngularAgility#126]
This may be the same bug as 125, but I am unsure so it's getting submitted as a new one. 

I am running into issues where I have a list of objects and each of those is being edited within the same form.  To do this, I am passing each object into a directive which has aa-form-group inputs.  It appears that validation is only disappearing when the last bound item satisfies the validation, yet the form will not submit until all items pass validation.

The README.md has instructions as to how to repeat the issue.

[Plnkr](http://plnkr.co/edit/UUAy52sXlqoDndPSqlwR?p=preview)

**Comment by johnculviner** [comment]
Hey! Yeah it's getting confused because you have the same field names in the same form multiple times. This should fix it for you (just need to make multiple forms, angular and AA have no problem with multiple nested forms: http://plnkr.co/edit/sdHXdBj5FxNnvysMaMZ1?p=preview

This fix it for you?

**Comment by erikruggles** [comment]
Yup.  That did the trick.  I didn't see the advanced tab for the form extensions demo.  I do now :/
