### ISSUE TITLE
Error messages are duplicated for input-boxes

### ISSUE THREAD

**Issue by magicmanam** [AngularAgility/AngularAgility#127]
Error messages are duplicated for input-boxes with the same name on the one form (although they are located in isolated scopes - ng-repeat is used).

Use case: model is an array of editable objects with the same structure (e.g. ToDo app).
Here a [plunk](http://plnkr.co/edit/6WlucSmebqfkqMPmeoIS?p=preview) with steps to reproduce.

**Comment by johnculviner** [comment]
Hey, this is more of an angular thing than anything else. you can't have multiple fields in the same form with the same name. plunk updated: http://plnkr.co/edit/JYGutSNqTmCa4gOxsfva?p=preview

also take a look at this example doing something similar. Enjoy!

http://angularagility.herokuapp.com/#/formExtensions/formExtensions/advanced

**Comment by magicmanam** [comment]
Thank you, it works now!
