### ISSUE TITLE
difference between AngularAgility and AngularAgility.Net?

### ISSUE THREAD

**Issue by lstockton** [AngularAgility/AngularAgility#130]
I know these are similarly named, and there can be an assumption that the .Net one is just a version of AngularAgility made specifically for .Net, but I wanted to check first.
What is the difference between the two?
I'm developing in a .Net environment, so I just want to know which version I need to download.

**Comment by johnculviner** [comment]
I didn't work on it but I think the goal of that one was to generate angular ng-model stuff using Razor syntax bound to underlying strongly typed models. Sort of like this perhaps? https://github.com/johnculviner/FluentKnockoutHelpers I don't think it was ever used or fully baked so stick with this one!
