### ISSUE TITLE
Consider adding angular-agility to NPM?

### ISSUE THREAD

**Issue by SenHeng** [AngularAgility/AngularAgility#133]
As more people are removing bower out of their workflows, woud you consider making it installable directly via npm?

**Comment by johnculviner** [comment]
Sounds good to me! I don't really use bower anymore either :)

I'll put er on NPM...

**Comment by johnculviner** [comment]
Done, enjoy!

**Comment by SenHeng** [comment]
Thanks for the rapid response! :fireworks:
