### ISSUE TITLE
There are some validation errors: - But none shown in ul

### ISSUE THREAD

**Issue by eigotec** [AngularAgility/AngularAgility#134]
Hi,

I have all my fields valid, but when clicking submit i get the notify pop-up saying 'There are some validation errors:' but nothing else. I checked the html with the webkit inspector, but the ul is empty.
Any ideas would be appreciated. Thanks

**Comment by johnculviner** [comment]
hmm please get me a plunkr with steps to reproduce and ill take a look

**Comment by eigotec** [comment]
Ok thanks. Appreciate the crazy fast response :-)

**Comment by eigotec** [comment]
Ok Plunkr isn't let me save at the moment but let me see what i can do.

**Comment by eigotec** [comment]
Not sure what the issue was, but its sorted now. Cheers
