### ISSUE TITLE
Changelog Needed

### ISSUE THREAD

**Issue by mendeza** [AngularAgility/AngularAgility#140]
Please consider maintaining a simple Changelog, updated with each versioning increment.

**Comment by mendeza** [comment]
Hi @johnculviner - Thank you for your project. Is it onerous to maintain a changelog per version? I think many more people than just me would really appreciate it.

**Comment by johnculviner** [comment]
Hi @mendeza, I will try to remember do that for future changes. For now you should be able to roughly refer to the commit history. Thanks for the feedback!
