### ISSUE TITLE
NavigateAway modal shows up on state change even though form doesn't change

### ISSUE THREAD

**Issue by spoddutu** [AngularAgility/AngularAgility#146]
When moving from one state to another state without change in form, the navigate away popup is shown.  How to avoid the same ?

**Comment by johnculviner** [comment]
hmmm it must think it's dirty for some reason. are you loading data in/setting values after the form is initialized? if you don't want to worry about that you can just disable the feature entirely... thoughts?

**Comment by spoddutu** [comment]
Hmm, i just realized that in one of the form we have only filter criteria and on apply of any of those filter(s) it is setting $changed to true. This is causing the navigate away modal pop's up.

So can we disable navigate away for a specific  form ?

**Comment by johnculviner** [comment]
Yup: 

https://github.com/AngularAgility/AngularAgility/blob/b283ee6a296d7fc6b76539d2e7b7ee2787c1a37c/demo/app/formExtensions/advanced.html#L62

Feel free to do some PRs to add more docs as you find things. That is one lacking thing with this library unfortunately...

**Comment by spoddutu** [comment]
Below code doesn't work
div ng-form="xyz" on-navigate-away-strategy="none">

Am i missing something here ?

**Comment by johnculviner** [comment]
Not sure, try giving the debugger a whirl:

https://github.com/AngularAgility/AngularAgility/blob/2bed4475891ba7ff0e3e57ed026db7f41de5c6e9/src/formExtensions/directives/ngForm.js#L90
