### ISSUE TITLE
Module not found error when trying to import angular-agility

### ISSUE THREAD

**Issue by senhongo** [AngularAgility/AngularAgility#154]
Had this error while converting an old project over to ES6 modules and webpack and attempting to import aa.

Error message
```
ERROR in ./~/angular-agility/Gruntfile.js
Module not found: Error: Can't resolve 'matchdep' in '/Users/ST47/projects/cyberagent/control/node_modules/angular-agility'
 @ ./~/angular-agility/Gruntfile.js 5:2-21
 @ ./app/scripts/napp.ts
 @ multi (webpack)-dev-server/client?http://localhost:9000 webpack/hot/dev-server ./app/scripts/napp.ts
```

napp.ts - simply attempting to import aa causes the error.
```
import 'angular-agility';
```

For now the error can be solved by simply pointing the export to the dist folder
`import 'angular-agility/dist/angular-agility';`

I'm guessing the error is because there isn't an `index.js` file in the root angular-agility direction that exports the aa module.

**Comment by roobie** [comment]
One way to solve this is to update `package.json` so that the field `main` points to `dist/angular-agility`, which would indicate to `require(..)` and `import` that it is the file to import.
