### ISSUE TITLE
Submitting twice when aa-submit-form is used with type="submit"

### ISSUE THREAD

**Issue by alejandromagnorsky** [AngularAgility/AngularAgility#155]
Hello,

As specified in https://www.w3schools.com/tags/tag_button.asp , the button HTML tag should always have the type attribute.
The problem is that if the button has type="submit", then on enter, it submits twice which is not as intended.

Thanks.

**Comment by johnculviner** [comment]
for now I'd suggest avoiding putting type="submit" on the button as it can also trigger html5 form validation which you probably also don't want (if it's in a form). w3schools suggests you put something on there but it is definitely not required by any stretch of the imagination. w3schools also isn't a very definitive source of information (but dont get me wrong, useful!) feel free to send me a PR if you'd like to get it how you'd like to see it
