### ISSUE TITLE
aaNotify not showing notification when directive is inside view of controller

### ISSUE THREAD

**Issue by tecnoloco** [AngularAgility/AngularAgility#156]
When I run a controller and try to run methods of aaNotify at the beggining of it, like

```javascript

angular.module('myApp').controller('myContoller', function(aaNotify){
   aaNotify.error('Error message', {ttl:0})
})

```

and the direcitve aaNotify is inside de view of this controller it does not show the notification, only if it side outside the view of the controller. A work arround is to put aaNotify.error() insdie a $timeout but is not a good solution.

```javascript

angular.module('myApp').controller('myContoller', function(aaNotify, $timeout){
   $timeout(function(){aaNotify.error('Error message', {ttl:0})}, 10)
})

```

**Comment by johnculviner** [comment]
Yeah unfortunately this is a classic angular lifecycle type issue: The notify directive doesn't exist yet until after the controller renders its contents so there is no way aanotify will get the message through the way it does emit/on. I would suggest placing it in a more global location (perhaps 1 per app!) to eliminate the issue which is how it was intended to be used. Thoughts?
